# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'


steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300' # replace this value with the version that you need for your project

- script: dotnet restore FSBOL.sln

- script: dotnet restore FSBOLJS.sln

- script: dotnet restore FSBOLTests.sln

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FSBOL.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FSBOLJS.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FSBOLTests.sln'
    arguments: '--configuration Release'
